services:
  amneziawg:
    build: .
    image: vernette/amneziawg-client:v1.0.20260223
    container_name: amneziawg-client
    restart: always
    # Uncomment one of the following if needed
    # Otherwise, the interface will only be accessible within this container
    # network_mode: "host"                  # expose interface to the host
    # network_mode: "service:some_service"  # share interface with another container
    volumes:
      - ./configs:/etc/amnezia/amneziawg:ro
    # Required only in userspace mode (no amneziawg kernel module on the host)
    # If you use the kernel module, comment this out
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
